import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastRoot } from "../components/shared/toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rural Pulse",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg",
  }
};


export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <ToastRoot />
      </body>
    </html>
  );
}
